# Config file for automatic testing at travis-ci.org

sudo: false

addons:
  apt:
    packages:
    - libeccodes0

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: TOXENV=docs
  - python: 3.5
    env: TOXENV=qc

install:
  - pip install tox tox-travis
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
